CREATE TABLE `merchant_alias` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Autoincrement Primary Key',
  `alias_id` varchar(525) DEFAULT NULL ,
  `is_agent_alias` varchar(525) DEFAULT NULL ,
  `merchant_id` varchar(525) DEFAULT NULL ,
  `merchant_category_code` varchar(525) DEFAULT NULL ,
  `payload_format_indicator` varchar(525) DEFAULT NULL ,
  `point_of_initiation_method` varchar(525) DEFAULT NULL ,
  `transaction_currency_code` varchar(525) DEFAULT NULL ,
  `tip_convenience_fee_indicator` varchar(525) DEFAULT NULL ,
  `convenience_fee_amount` varchar(525) DEFAULT NULL ,
  `convenience_fee_percentage` varchar(525) DEFAULT NULL ,
  `recipient_name` varchar(1024) DEFAULT NULL ,
  `city` varchar(525) DEFAULT NULL ,
  `country` varchar(525) DEFAULT NULL ,
  `terminal_id` varchar(50) DEFAULT NULL ,
  `postal_code` varchar(50) DEFAULT NULL ,
  `email` varchar(525) DEFAULT NULL ,
  `phone` varchar(50) DEFAULT NULL ,
  `create_status` varchar(100) DEFAULT NULL ,
  `update_status` varchar(100) DEFAULT NULL ,
  `delete_status` varchar(100) DEFAULT NULL ,
  `error_reason` text ,
  `status` varchar(16) DEFAULT NULL COMMENT 'HTTP status of response',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When log was created',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT 'Last time log was updated',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `merchant_alias` CHANGE COLUMN `status` `status` varchar(16) DEFAULT NULL;
