package com.visa.service.model.constant;

/**
 * Created by abdussamad.olaiya on 23/06/2019.
 */
public enum CardType {
  MASTERCARD, VISA_PLATINUM, VISA_REWARDS, VISA_SELECT, VISA_GOLD, PRIVATE_LABEL, PRIVATE_LABEL_PREPAID,
  PRIVATE_LABEL_BASIC, PRIVATE_LABEL_STANDARD, PRIVATE_LABEL_ENHANCED, PRIVATE_LABEL_SPECIALIZED, PRIVATE_LABEL_PREMIUM,
  PROPRIETARY, VISA_PURCHASING, VISA_PURCHASING_WITH_FLEET, VISA_GOVERNMENT_PURCHASING, VISA_GOVERNMENT_PURCHASING_WITH_FLEET,
  VISA_COMMERCIAL_AGRICULTURE, VISA_COMMERCIAL_TRANSPORT, VISA_COMMERCIAL_MARKETPLACE, VISA_TRAVEL_MONEY, VISA_V_PAY,
  VISA_ELECTRON, VISA_TRADITIONAL, AMERICAN_EXPRESS, VISA_TRADITIONAL_REWARDS, VISA_SIGNATURE, VISA_SIGNATURE_PREFERRED, DISCOVER, DINERS,
  VISA_CLASSIC, VISA_BUSINESS, PROPRIETARY_ATM, VISA_SIGNATURE_BUSINESS, VISA_BUSINESS_CHECK_CARD, VISA_BUSINESS_ENHANCED,
  VISA_INFINITE_BUSINESS, VISA_BUSINESS_REWARDS, VISA_INFINITE, VISA_INFINITE_PRIVILEGE, VISA_UHNW, VISA_HEALTHCARE, JCB,
  VISA_CORPORATE_T_AND_E
}
