package com.visa.service.model.constant;

/**
 * @author Abdussamad
 */
public enum Status {
  SUCCESSFUL, FAILED, ACTIVE, INACTIVE, NEW, PENDING, PROCESSED, SUCCESS,
  CREATION_SUCCESSFUL, UPDATE_SUCCESSFUL, DELETION_SUCCESSFUL,
  CREATION_FAILED, UPDATE_FAILED, DELETION_FAILED
}
